<?php

/**
 * @file
 * Provides hook implementations for the Station Playlist module.
 */

use Drupal\Core\Url;
use Drupal\node\NodeInterface;

/**
 * Implements hook_node_links_alter().
 */
function station_playlist_node_links_alter(array &$links, NodeInterface $entity, array &$context) {
  $links_to_add = [];
  if ($context['view_mode'] == 'full') {
    switch ($entity->bundle()) {
      case 'station_program':
        $links_to_add['station_playlist_view'] = [
          'title' => t('View all playlists'),
          // @todo Create a real route for this.
          'url' => Url::fromRoute('<front>'),
        ];
        if ($entity->access('update')) {
          $links_to_add['station_playlist_add'] = [
            'title' => t('Add new playlist'),
            // @todo Create a dedicated route to prefill the program.
            'url' => Url::fromRoute('node.add', ['node_type' => 'station_playlist']),
          ];
        }
        break;

      case 'station_playlist':
        $links_to_add['station_program_view'] = [
          'title' => t('View program'),
          'url' => $entity->station_playlist_program->entity->urlInfo(),
        ];
        break;

    }
  }
  if ($links_to_add) {
    $links['station_playlist'] = [
      '#theme' => 'links__node__station_playlist',
      '#attributes' => ['class' => ['links', 'inline']],
      '#links' => $links_to_add,
    ];
  }
}
