<?php

/**
 * Implements hook_node_info().
 */
function station_program_node_info() {
  return array(
    'station_program' => array(
      'name' => t('Program'),
      'base' => 'node_content',
      'has_title' => TRUE,  
      'title_label' => t('Title'),
      'description' => t('A radio program that you can schedule.'),
    ),
    'station_archive' => array(
      'name' => t('Audio'),
      'base' => 'node_content',
      'has_title' => TRUE,  
      'title_label' => t('Title'),
      'description' => t('A audio file.'),
    ),
  );
}
/**
 * Implements hook_help().
 */
function station_program_help($path, $arg) {
  switch ($path) {
    case 'admin/config/station/program':
      return t("These settings allow you to configure the station's program node.");
  }
}

/**
 * Implements hook_menu().
 */
function station_program_menu() {
  $items['station/autocomplete/program'] = array(
    'title' => 'Program autocomplete',
    'page callback' => 'station_program_autocomplete',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function station_program_permission() {
  return array(
    'administer station programs' => array(
      'title' => t('administer station programs'),
    ),
    'view station program content' => array(
      'title' => t('view station program content'),
    ),
  );
}

/**
 * Implements hook_node_access().
 */
function station_program_node_access($node, $op, $account) {
  $type = is_string($node) ? $node : $node->type;

  if ($type == 'station_program') {
    if (user_access('administer station programs', $account)) {
      return NODE_ACCESS_ALLOW;
    }

    switch ($op) {
      case 'view':
        if ($node->status && user_access('view station program content', $account)) {
          return NODE_ACCESS_ALLOW;
        }

      case 'update':
        if (user_access('edit own station_program content', $account)) {
          // If the schedule is enabled, let DJs edit the program.
          if (module_exists('station_schedule')) {
            if (!empty($node->field_station_program_dj)) {
              foreach ($node->field_station_program_dj as $delta => $user) {
                if ($user['uid'] == $account->uid) {
                  return NODE_ACCESS_ALLOW;
                }
              }
            }
          }
        }
    }
  }
  return NODE_ACCESS_IGNORE;
}

/**
 * Implements hook_validate().
 */
function station_program_node_validate($node, $form, &$form_state) {
  if ($node->type == 'station_program') {
    $css_class = field_get_items('node', $node, 'field_station_program_css_class');
    //if (!preg_match('/^-?[_a-zA-Z]+[_a-zA-Z0-9-]*$/', $css_class[0]['value'])) {
    if (!preg_match('/^[_a-zA-Z0-9-]*$/', $css_class[0]['value'])) {
      form_set_error('field_station_program_css_class', 'Not a valid css class name.');
    }
  }
}

/**
 * Retrieve a pipe delimited string of autocomplete suggestions for existing programs
 */
function station_program_autocomplete($string = '') {
  $matches = array();
  $result = db_query_range("SELECT DISTINCT title, nid FROM {node} WHERE type = :type AND LOWER(title) LIKE LOWER(:str) AND status = :status ORDER BY title", 0, 10, array(':type' => 'station_program', ':status' => 1, ':str' => '%' . $string . '%'));
  foreach ($result as $program) {
    $matches[$program->title] = check_plain($program->title);
  }
  print drupal_json_encode($matches);
  exit();
}
